# Generated by Django 5.2.13 on 2026-04-19 23:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='attempt',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='started', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='group_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='student_identifier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
