# Generated by Django 5.2.13 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_attempt_options_attempt_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='selected_multi_answers', to='main.answeroption'),
        ),
    ]
